version: '3'

services:
  api:
    build: api
    command: ["python", "boot.py"]
    environment:
      - HOST=0.0.0.0
      - PORT=6543
      - OPEN_WEATHER_API_KEY=GET_KEY_FROM openweathermap.org
      - OPEN_WEATHER_API_URL=https://api.openweathermap.org/data/2.5/weather
    ports:
      - "6543:6543"

    volumes:
      - ./api:/api

  app:
    build: app
    command: ["npm", "start"]
    volumes:
      - ./app:/app
      - node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  node-modules:
